# Generated by Django 6.0.3 on 2026-03-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business & Management'), ('healthcare', 'Healthcare'), ('arts', 'Arts & Design'), ('science', 'Science & Research'), ('education', 'Education & Teaching'), ('finance', 'Finance & Accounting'), ('law', 'Law & Legal'), ('engineering', 'Engineering'), ('marketing', 'Marketing & Communication')], max_length=30)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated list of skills')),
                ('avg_salary', models.CharField(max_length=50)),
                ('growth_outlook', models.CharField(max_length=100)),
                ('icon', models.CharField(default='briefcase', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('video', 'Video Tutorial'), ('article', 'Article / Blog'), ('certification', 'Certification'), ('workshop', 'Workshop')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('domain', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business & Management'), ('healthcare', 'Healthcare'), ('arts', 'Arts & Design'), ('science', 'Science & Research'), ('education', 'Education & Teaching'), ('finance', 'Finance & Accounting'), ('law', 'Law & Legal'), ('engineering', 'Engineering'), ('marketing', 'Marketing & Communication')], max_length=30)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('skills_covered', models.TextField(blank=True, default='', help_text='Comma-separated list of skills')),
                ('career_paths', models.ManyToManyField(blank=True, related_name='resources', to='career_edu.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('student', 'Student'), ('fresher', 'Fresher (0-1 years)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid-Level (3-6 years)'), ('senior', 'Senior (6+ years)')], default='student', max_length=20)),
                ('current_skills', models.TextField(blank=True, default='', help_text='Comma-separated list of your current skills')),
                ('bio', models.TextField(blank=True, default='')),
                ('target_role', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_users', to='career_edu.careerpath')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
